openapi: 3.0.3
info:
  title: Hello User Service
  description: Hello User Servise（APIの説明）
  version: 0.0.1
servers:
- url: http://localhost:8088
paths:
  /hello:
    post:
      tags:
      - user
      summary: hello user
      operationId: user#hello
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloRequestBody'
            example:
              name: Et ea ea nesciunt quia eius.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponseBody'
              example:
                greet: Iure qui odio expedita.
components:
  schemas:
    HelloRequestBody:
      type: object
      properties:
        name:
          type: string
          description: user name
          example: Vel necessitatibus similique mollitia eaque doloremque.
      example:
        name: Autem fuga eos.
    HelloResponseBody:
      type: object
      properties:
        greet:
          type: string
          description: greet result
          example: Sit eum nostrum ullam quis velit incidunt.
      example:
        greet: Perspiciatis consequatur impedit quos vero.
tags:
- name: user
  description: User Serviceドメインモデル単位くらいのニュアンス
